version: '3'

services:
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - "./api/swagger.yaml:/swagger.yaml"
    environment:
      SWAGGER_JSON: /swagger.yaml
    ports:
      - "8080:8080"

  architect:
    image: golang:1.10
    command: /bin/sh -c "eval `ssh-agent` && go run cmd/vci-architect/main.go"
    working_dir: /go/src/github.com/velocity-ci/velocity/backend/
    environment:
      # LOG_LEVEL: debug
      ADMIN_PASSWORD: admin
      JWT_SECRET: local
      BUILDER_SECRET: local
      PORT: 80
    ports:
      - "80:80"
    volumes:
      - "./:/go/src/github.com/velocity-ci/velocity/backend/"
      - "./architect_data:/opt/velocityci"

  builder:
    image: golang:1.10
    command: /bin/sh -c "eval `ssh-agent` && go run cmd/vci-builder/main.go"
    working_dir: /go/src/github.com/velocity-ci/velocity/backend/
    environment:
      LOG_LEVEL: debug
      BUILDER_SECRET: local
      ARCHITECT_ADDRESS: http://architect
    volumes:
      - "./:/go/src/github.com/velocity-ci/velocity/backend/"
      - "/opt/velocityci:/opt/velocityci"
      - "/var/run/docker.sock:/var/run/docker.sock"
